### ISSUE TITLE
rss订阅能否增加支持只发送标题和原文链接的配置

### ISSUE THREAD

**Issue by forchannot** [MountainDash/nonebot-bison#143]
rt，目前的rss订阅会把整个文章发回来，也没有返回原文链接（我用的image模式），导致阅读起来比较麻烦。而且也没有支持去重，标题和内容都一样的话会显示两次（如订阅github仓库的commit）

**Comment by felinae98** [comment]
请补充一下订阅的rss源，现在发送的内容

**Comment by forchannot** [comment]
针对第一个阅读麻烦，订阅链接为https://rss.cherishmoon.fun/tencent/pvp/newsindex/gg?filter_title=更新 ，发送内容为
![Z@AJW~}$YJW7G T D$LFFHF](https://user-images.githubusercontent.com/100580891/201906035-edb40592-dc55-4edd-94e4-74885e302d2b.PNG)
针对第二个标题和内容一样没有去重，订阅链接为https://rss.cherishmoon.fun/github/file/CMHopeSunshine/LittlePaimon/Bot/LittlePaimon/ ，返回内容为
7](https://user-images.githubusercontent.com/100580891/201906193-1af729ae-32c5-4063-88b2-b13978d29afe.PNG)
二者都没有返回原链接地址

**Comment by forchannot** [comment]
第二个问题返回内容的图好像没显示出来，这里补一下
![${_V{KBTHI@(REA3K K~第二个返回内容的图好像没显示出来，这里补一下
7](https://user-images.githubusercontent.com/100580891/201906634-e48ee045-b452-4b49-a431-7aff04641f81.PNG)

**Comment by forchannot** [comment]
补充一下，如果采用图片形式发送rss订阅，不会将链接发出来。其他订阅源会将链接也一并发出来

**Comment by forchannot** [comment]
我看貌似新版说是rss图片模式也能发链接了，但是我这里并没有发送，但是后台日志是有链接的，rss的订阅链接为[王者荣耀公告](https://rss.lktuchaung.buzz/tencent/pvp/newsindex/gg?filter%20title=%E6%9B%B4%E6%9%206%B0)@UKMeng
![image](https://github.com/felinae98/nonebot-bison/assets/100580891/ce99e0f2-3b28-488d-81a5-5fd020883a46)
![image](https://github.com/felinae98/nonebot-bison/assets/100580891/bf54fa26-2e39-4135-97a0-5e0f6a5d3232)
![a463201e678c7669362190dba2489edc_720](https://github.com/felinae98/nonebot-bison/assets/100580891/3ce16dc9-9c5d-493d-b7a7-66a64427d4cd)

**Comment by UKMeng** [comment]
> 我看貌似新版说是rss图片模式也能发链接了，但是我这里并没有发送，后台日志是有链接的，rss的订阅链接为[王者荣耀公告](https://rss.lktuchaung.buzz/tencent/pvp/newsindex/gg?filter%20title=%E6%9B%B4%E6%9%206%B0)@UKMeng
> 
> 图片

我才发现这个文件变动不知咋地没传上去，下个版本应该能修好吧

**Comment by AzideCupric** [comment]
> github的RSS源没有release的注释的问题能不能也修一下
> 
> ![image](https://user-images.githubusercontent.com/57741549/258306604-2f61a537-eba0-4cac-a0e6-ef3a688d4a55.png) ![image](https://user-images.githubusercontent.com/57741549/258306656-3ac35574-6d4a-4ed9-aec4-e456f8bd1a96.png)

如果这是github自己的特殊字段的话在rss这个平台适配未免过于丑陋，如果可以的话要不来贡献一个针对github的platform（

**Comment by AzideCupric** [comment]
现在可以使用brief主题实现了喵
