### ISSUE TITLE
群聊中添加订阅的问答回复错误

### ISSUE THREAD

**Issue by kexue-z** [MountainDash/nonebot-bison#18]
```
A: @bot 加订阅
Bot: {_prompt}
A: rss
Bot: {_prompt}
A: [rss链接]
Bot: 添加 XXX 成功
```

**Comment by felinae98** [comment]
可能因为nonebot版本过低，请更新nonebot版本

**Comment by kexue-z** [comment]
nonebot2 = "2.0.0a16"
是最新的吧

**Comment by kexue-z** [comment]
https://github.com/felinae98/nonebot-hk-reporter/blob/ad6bd9c4dd7fb95cbf7f78014f8340b34ffff68f/src/plugins/nonebot_hk_reporter/config_manager.py#L49
这些 `{_prompt}` 都被直接输出了

**Comment by felinae98** [comment]
破坏性更新见：https://github.com/nonebot/discussions/discussions/41
