### ISSUE TITLE
一个傻瓜式提案，基本使用案例，quickstart

### ISSUE THREAD

**Issue by ghost** [MountainDash/nonebot-bison#239]
因为傻瓜式提案，我长话短说。
能不能在readme中多一点基础的使用样例的图片截图，quickstart的样例。
文档一直在说明参数，很详尽，但是没有给很好的例子。
我也是尝试才知道是 "/查询订阅" 而不是 "查询订阅"
而  到底是   “添加订阅“还是“/添加订阅”，输入命令之后，有没有返回信息，我都不知道。看nonebot的运行情况，应该是没匹配上。
那么正常的格式又应该怎么写呢？
![QQ截图20230417195659](https://user-images.githubusercontent.com/57578855/232477599-de5e22bd-c223-4dd9-bc23-bb3756fe7d10.jpg)
主要是从接近普通用户的角度。如果我的发言不妥，请Administer删除我的issue

**Comment by jack-SAI** [comment]
我进行了一些配置。在配置了浏览器和转图片之后。总之配置是生效的，查询订阅的返回被渲染为了图片。
但是基本的怎么添加订阅，我似乎依然没有掌握正确的使用方法。

**Comment by AzideCupric** [comment]
> 能不能在readme中多一点基础的使用样例的图片截图，quickstart的样例。
> 文档一直在说明参数，很详尽，但是没有给很好的例子。

总所周知，程序员最讨厌的事之二，用的项目没有文档和要给项目写文档(
咕咕咕，有时间会尽量写的(

> 而 到底是 “添加订阅“还是“/添加订阅”，输入命令之后，有没有返回信息，我都不知道。

命令是否有前缀符号取决于你的[nonebot配置](https://v2.nonebot.dev/docs/appendices/config#%E5%86%85%E7%BD%AE%E9%85%8D%E7%BD%AE%E9%A1%B9)，文档里有稍微提到过: [“使用“章节的第一个WARNING](https://nonebot-bison.netlify.app/usage/#%E4%BD%BF%E7%94%A8)

> 但是基本的怎么添加订阅，我似乎依然没有掌握正确的使用方法。

目前BISON的添加订阅命令是一个逐步进行的过程，想要添加订阅，直接发送`/添加订阅`命令即可，不用附带其他字符，之后BISON会提示如何继续下一步操作

**Comment by felinae98** [comment]
确实在考虑更新readme
（btw，Administrator写错了
