### ISSUE TITLE
[建议]能否添加功能通过代理访问订阅

### ISSUE THREAD

**Issue by sherlockHlb** [MountainDash/nonebot-bison#242]
建议.
nonebot_bison | network connection error: <class 'httpx.PoolTimeout'>, url: https://www.youtube.com/feeds/videos.xml?channel_id=UCYjB6uufPeHSwuHs8wovLjg
无法访问RSS

**Comment by sherlockHlb** [comment]
04-22 17:35:12 [WARNING] nonebot_bison | network connection error: <class 'httpx.ReadTimeout'>, url: https://m.weibo.cn/api/container/getIndex?containerid=1076036190405002
甚至有时候连微博都看不了

**Comment by AzideCupric** [comment]
https://github.com/felinae98/nonebot-bison/pull/71
文档: [https://nonebot-bison.netlify.app/usage/#%E9%85%8D%E7%BD%AE] BISON_PROXY

**Comment by sherlockHlb** [comment]
network connection error: <class 'httpx.ConnectTimeout'>, url: https://rsshubzzz.vercel.app/t66y/15
添加了代理依然不行.

**Comment by sherlockHlb** [comment]
04-26 09:16:14 [WARNING] nonebot_bison | network connection error: <class 'httpx.ReadTimeout'>, url: https://m.weibo.cn/api/container/getIndex?containerid=1076036064800364
添加代理了仍然是出现这个错误
![image](https://user-images.githubusercontent.com/30238046/234441411-57da94d2-253b-41fc-9da5-36f39bb4707f.png)

**Comment by sherlockHlb** [comment]
而且不断提醒

04-30 02:43:46 [WARNING] logging | Run time of job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2023-04-30 02:43:47 CST)" was missed by 0:00:01.969608
04-30 02:43:46 [WARNING] logging | Run time of job "Scheduler.exec_fetch (trigger: interval[0:00:10], next run at: 2023-04-30 02:43:49 CST)" was missed by 0:00:06.157668

**Comment by Nelocompne** [comment]
> network connection error: <class 'httpx.ConnectTimeout'>, url: https://rsshubzzz.vercel.app/t66y/15 添加了代理依然不行.
> 
> #BISON BISON_PROXY=http://127.0.0.1:1090

将参数加上引号如何？我是这样写的（能正常工作）：
```yml
BISON_PROXY: 'http://localhost:port'
```
