### ISSUE TITLE
上版本能推送的RSS源，这版本出了问题，麻烦大佬看一下

### ISSUE THREAD

**Issue by zzz6839** [MountainDash/nonebot-bison#289]
## 环境

- nonebot-bison 版本：docker latest 7e694e1f445762c220374d6fef58f93fc9c8c458b71185b82029e9b0834de20f
- nonebot 版本：docker
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
  2. 使用 poetry/pdm 等现代包管理器安装
  3. 通过 pip install 安装
  4. 克隆或下载项目直接使用
- 操作系统：X86_64

## 问题

https://rito-news.iamantosik.me/lol/zh-tw/status.tw.atom
这个源在上版本能够推送变化，这个版本没法推送了，且日志没有相关信息，找不到问题原因

## 日志

```
无相关日志信息
```

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
提供一下变化前后的rss文件？不然不好排查

**Comment by UKMeng** [comment]
用这个源跑测试没遇到问题，等源更新后再看看。或者可能是别的原因。

**Comment by UKMeng** [comment]
观察到目前https://status.riotgames.com/lol?region=tw2&locale=zh_TW在05:57新更新了一条但是https://rito-news.iamantosik.me/lol/zh-tw/status.tw.atom在08:26仍然没有变化。bison的机制是就算是新推文但是超过2小时就不推送，可能是这个原因。

**Comment by UKMeng** [comment]
给的两个文件看起来最新的entry都是同一个

**Comment by felinae98** [comment]
还是提供一下rss地址变化前后的xml内容，不然不好排查

**Comment by felinae98** [comment]
那确实很可能是网络原因，可以加上代理配置
