### ISSUE TITLE
BISON_OUTER_URL的配置文档不明确

### ISSUE THREAD

**Issue by SherkeyXD** [MountainDash/nonebot-bison#308]
## 环境

- nonebot-bison 版本：0.8.0
- nonebot 版本：1.2.2
- 安装方式：通过 nb-cli 安装
- 操作系统：Debian

## 问题

无论设置 BISON_OUTER_URL 为 `http://服务器ip:8080/bison/` 还是 `http://0.0.0.0:8080/bison/`，访问后台网页都返回 502 错误

若设置为 localhost 并启用反代，出现 #277 的问题

## 日志

```
无相关日志
```

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
还是需要提供你的网络和部署环境

**Comment by SherkeyXD** [comment]
bot 部署在腾讯云服务器上 防火墙的对应端口都开放了

**Comment by felinae98** [comment]
如果url不包含/bison/呢，会返回什么

**Comment by SherkeyXD** [comment]
> 如果url不包含/bison/呢，会返回什么

同样502

**Comment by felinae98** [comment]
正常情况应该返回404，如果是502可能需要排查一下反代或者是访问链路的问题

**Comment by SherkeyXD** [comment]
我大概懂了 现在Bison的web管理界面是开在和Bot同一个端口的，这个配置项只是为了修改Bot发送的提醒
把反代目标设置为Bot的端口就解决问题了

**Comment by SherkeyXD** [comment]
文档是不是最好改改 感觉这样有点迷惑）

**Comment by AzideCupric** [comment]
既然这样 要不pr一个？（

**Comment by SherkeyXD** [comment]
其实感觉更好的解决方案是根据配置的url来起配置界面（？

**Comment by AzideCupric** [comment]
主要是做不到（

**Comment by SherkeyXD** [comment]
那改成只填ip，端口用读到的Nonebot端口？

**Comment by AzideCupric** [comment]
之前提过，也是做不到(

**Comment by SherkeyXD** [comment]
<img width="862" alt="f02f4cb2378b536a6ab581e776fc0af9" src="https://github.com/MountainDash/nonebot-bison/assets/57581480/097f7484-1cc0-4d65-8511-4d9b8e295f64">

那这边是什么（

**Comment by AzideCupric** [comment]
好像确实 要不你试试看(?

**Comment by SherkeyXD** [comment]
那 `bison_outer_url` 的默认值改成 `http://localhost` 吗
感觉是不是换个名字（？

**Comment by AzideCupric** [comment]
这个localhost用<your ip>什么的替换一下吧，免得有误解

**Comment by felinae98** [comment]
> 那改成只填ip，端口用读到的Nonebot端口？

也倒不是做不到，如果使用 docker 部署或者用 nginx 做了反向代理，那么从如何从外部访问 nonebot 是肯定需要额外配置的。当然修改一下默认值是可以的

**Comment by SherkeyXD** [comment]
或者加个检测，当用户填写的 `bison_outer_url` 中的端口号与 nonebot 端口号不一致的时候提醒一句？

然后文档补充一下说明
