### ISSUE TITLE
长微博推送时微博内容不全

### ISSUE THREAD

**Issue by siuze** [MountainDash/nonebot-bison#446]
## 环境

- nonebot-bison 版本：0.8.2
- nonebot 版本：2.1.2
- 安装方式：通过 pip install 安装
- 操作系统：X86_64

## 问题

今天鹰角发了一条比较长的公告，发现QQ群里推送的内容不全，末尾有省略号。  
这个是微博爬虫的问题还是bison设计使然（防止消息过长）？如果是符合预期的设计，是否可以自定义配置为不省略内容，或者是否考虑分成多条消息？

![image](https://github.com/MountainDash/nonebot-bison/assets/54578647/e68e2792-8f0e-473f-8d83-6e86b42fc1ac)
![image](https://github.com/MountainDash/nonebot-bison/assets/54578647/2c260311-2e0f-4705-b84b-1da066918ea8)

- [x] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [x] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
是防止消息过长导致风控的设计应该 ~而且是定死的~
https://github.com/MountainDash/nonebot-bison/blob/9766e400fa750ce1fe437c58e4fd7e42832b27c9/nonebot_bison/post/post.py#L105-L106

后续可以考虑添加对应配置

**Comment by siuze** [comment]
> 是设计 ~而且是定死的~ 初衷应该是防止文本过长导致风控
> 
> https://github.com/MountainDash/nonebot-bison/blob/9766e400fa750ce1fe437c58e4fd7e42832b27c9/nonebot_bison/post/post.py#L105-L106
> 
> 后续可以考虑添加对应配置

感谢回复，另外主页README的加群链接是过期了吗？点击之后提示加群校验不通过

**Comment by felinae98** [comment]
868610060

**Comment by AzideCupric** [comment]
如果想显示全文的话这个版本可以选择设置 `bison_use_pic=True`
