### ISSUE TITLE
微博订阅：关注的人转发带图片的原文，结果不会发送原文的图片

### ISSUE THREAD

**Issue by ifwlzs** [MountainDash/nonebot-bison#527]
## 环境

- nonebot-bison 版本：0.9.2
- nonebot 版本：2.2.1
- 安装方式：1（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
  2. 使用 poetry/pdm 等现代包管理器安装
  3. 通过 pip install 安装
  4. 克隆或下载项目直接使用
- 操作系统：windows 2009 (19045.4710)

## 问题

订阅微博的博主，博主转发原文带有图片的推文，bison发出来的消息不包含原文的图片

## 日志

```
请在这里粘贴你的日志
```

- [ √] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [ √] 我确认在日志中去掉了敏感信息

**Comment by AzideCupric** [comment]
resolved by #554
